# Generated by Django 2.2.7 on 2020-02-22 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Landlord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentalProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type_of_property_listing', models.CharField(choices=[('APARTMENT', 'Apartment'), ('HOLIDAY_HOME', 'Holiday home'), ('SINGLE_FAMILY_HOME', 'Single family home'), ('COMMERCIAL', 'Commercial')], default='APARTMENT', max_length=50)),
                ('street', models.CharField(max_length=255)),
                ('borough', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentalpropertys', to=settings.AUTH_USER_MODEL)),
                ('landlord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentalpropertys', to='rental.Landlord')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_required', models.BooleanField(default=True)),
                ('other_terms', models.TextField(blank=True)),
                ('rentalproperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='rental.RentalProperty')),
            ],
        ),
    ]
